### ISSUE TITLE
Setup incomplete always showing on Linux Mint 20.3 and Waterfox G4.0.7 (64-bit)

### ISSUE THREAD

**Issue by expandstudios** [null-dev/firefox-profile-switcher#24]
Extension installed with no issues, then the separate executable installed no worries and I have confirmed it is accessible via the command line. Browser extensions just persistently shows `Setup incomplete!` message.

![image](https://user-images.githubusercontent.com/4209626/153523082-2453a2e3-e284-466d-aeb2-dba68ff05580.png)

![image](https://user-images.githubusercontent.com/4209626/153523129-1e6390dd-992b-4765-9d61-eb12c907f5db.png)

![image](https://user-images.githubusercontent.com/4209626/153523147-ed192c63-d4d8-43fc-9d6e-a0d6340f209b.png)

I have tried restarting the browser as well as re-installing the browser extension, to no avail.

**Comment by null-dev** [comment]
The extension does have "unofficial" (because I don't test with them often) support for Firefox forks however it is undocumented and requires additional configuration. Here's how to set it up:

First, run the following two commands to show Waterfox where to find the executable:
```sh
mkdir -p ~/.waterfox/native-messaging-hosts
ln -s /usr/lib/mozilla/native-messaging-hosts/ax.nd.profile_switcher_ff.json ~/.waterfox/native-messaging-hosts/ax.nd.profile_switcher_ff.json
```

Now you need to instruct the profile switcher to search for Waterfox profiles instead of Firefox profiles. Run the below commands (make sure to replace `PUT THE PATH TO THE WATERFOX BINARY HERE` with the path to the waterfox binary, e.g. on my Arch system it's: `/usr/bin/waterfox-g4`):
```sh
mkdir -p ~/.config/firefoxprofileswitcher
echo '
{
    "browser_profile_dir": "'"$HOME"'/.waterfox",
    "browser_binary": "PUT THE PATH TO THE WATERFOX BINARY HERE"
}
' > ~/.config/firefoxprofileswitcher/config.json
```

Everything should work after that, let me know if you have any trouble.

**Comment by expandstudios** [comment]
Brilliant, worked perfectly, thank you!

> The extension does have "unofficial" (because I don't test with them often) support for Firefox forks however it is undocumented and requires additional configuration.

Yep, totally understand and I appreciate the quick and clear response.

**Comment by a7maadf** [comment]
@null-dev Thank you so much <3
